### PR TITLE
Update english translations - improved formatting and grammar

### PR DESCRIPTION
**Pull request by DeflateAwning**
* Improved grammar and sentence flow mistakes
* Improved formatting with mid-sentence and mid-button punctuation
* Updated a few translation keys (add `_button`, etc.)
* Improved "DC" and "ID" capitalization within English translations

### CODE REVIEW

**Comment by disk91** [comment]
Thank you so much for this contribution.
I won't merge it as it is because of the technical tag name modification that will create trouble in future merge from the different branches when not impacting the behavior.  
- Some of the translation are better but won't fit with the space in the UI (the reason why they were shorten). Like in lines 75 to 81
- Line 302 there is an "id," that may crash the translation loading.
For the rest, the proposal I really valuable.

I can propose two ways:
- You rework your pull request with only en.json modification, taking care of the impact in UI of the change, to be accepted
- I will include your modifications manually and add you as a contributor in the README.md

**Comment by DeflateAwning** [comment]
Thanks for reviewing it! Sure, I can re-work it a bit.

Can we please implement the changes of the "keys" for the translations though. Any translation for a call-to-action/button should have `_button` in its name, so that translators know that it is an action. 

Also, `signup_pmessage_3` is a less-good name than `check_email_spam_message`. 

How can we make these changes so that they won't "create trouble in the future". 

As far as I can tell, there is no one else with pending changes/branches (looking at Forks, and looking at the branches in this repo). If any owners of websites made changes and then didn't publish them back to the community, then that'll be on them to deal with any merge conficts (but again, I don't think there will be many/any; they were all very straight-forward renames). I was very miticulous to catch every instance.

**Comment by disk91** [comment]
> Thanks for reviewing it! Sure, I can re-work it a bit.
> 
> Can we please implement the changes of the "keys" for the translations though. Any translation for a call-to-action/button should have `_button` in its name, so that translators know that it is an action.
> 
> Also, `signup_pmessage_3` is a less-good name than `check_email_spam_message`.
> 
I'm not sure it's a really important thing but I can later work on this, it's improving code quality.

> How can we make these changes so that they won't "create trouble in the future".
> 
> As far as I can tell, there is no one else with pending changes/branches (looking at Forks, and looking at the branches in this repo). If any owners of websites made changes and then didn't publish them back to the community, then that'll be on them to deal with any merge conficts (but again, I don't think there will be many/any; they were all very straight-forward renames). I was very miticulous to catch every instance.

All the code you get on the community branch is now coming from a private instance I maintain. So basically it makes conflict with me. Language file is easy merge, plenty of little non functional little modification will be more complicated. This is why it will be better for me to incorporate this from the master and publish it into community later on.

**Comment by DeflateAwning** [comment]
This feels like a quirky way to handle a public-facing open source project, but I can deal with that.

Might be best if you handle the merging! Let me know if you need any help!

**Comment by disk91** [comment]
Most of the translations have been merged in en.json file.

**Pull request closed without merging**
