### PR TITLE
Re-apply missed translations from #90

### PR DESCRIPTION
**Pull request by DeflateAwning**
If you disagree with any of the changes here, please start a code review and comment on the specific changes you disagree with. We can discuss, and I will revert them in this branch if you disagree with them. This is how git/GitHub PRs are intended to be used. **Please merge this PR into main instead of trying to re-apply the changes some other way.**

The way that you're applying my PRs (e.g., #90) is not working, as you keep missing my edits. I intend for all changes in this PR to be applied to upstream (this repo).

This is my third time that I've requested that many of these specific changes be made in the translations.

### CODE REVIEW

**Comment by disk91** [comment]
Just the "Chirpstack" to "chirpstack", I use to have a capital and it has it in the other sentences as it's a "name";
For the rest it's great.
Waiting for the change to merge it directly.

**Comment by DeflateAwning** [comment]
Good catch! Fixed everywhere!

**Comment by disk91** [comment]
Pull request merged. Thank you for the contribution

**Comment by DeflateAwning** [comment]
Thank you!

**Pull request merged**
